<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CF1P74J" failures="1" tests="1" name="TestRunner.TestRunner" time="66.446" errors="0" timestamp="2023-06-22T14:52:54 IST" skipped="0">
  <testcase classname="TestRunner.TestRunner" name="runScenario" time="66.446">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinition.failrerunsteps.user_is_bello(failrerunsteps.java:39)
at âœ½.user is bello(file:///C:/Users/Dell/eclipse-workspace1/TESTNGPROJECT/src/test/resources/Features/failrerun.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.TestRunner -->
